apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demoapplication
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: restservice
  endpoints:
  - port: web
